.TH UnRiddle-QML 2020-11-24
.SH NAME
Unriddle-QML \- the 
.SH SYNOPSIS
.B  Unriddle-QML
.SH DESCRIPTION
you win.
.SH OPTIONS
Unriddle-QML.
.SH FILES
~/.config/unriddle-qml/unriddle-qml.conf
.RS
Per user configuration file.
.RE
.SH BUGS
If you find a bug, please notify the author.
.SH AUTHOR
Qiaoyong ZhongPavel Mosentsev <p.slant@gmail.com>
